### PR TITLE
Fixed sh.st

### PR DESCRIPTION
**Pull request by martinsik**
Hi, I fixed handler for sh.st. Their API has changed a bit. I ran tests and everything is passing.

### CODE REVIEW

**Comment by jkehler** [comment]
@martinsik Sorry I didn't see your PR until now. Does this fix still work? I won't have a chance to test it until the weekend. If it's still relevant I'll merge it.

**Comment by martinsik** [comment]
Hi @jkehler, I tested it now and it works fine!

**Comment by jkehler** [comment]
@martinsik great!. Just one last thing before I merge it. Could you please bump the version in unshortenit.__init__ and update the HISTORY.rst. Then I can take care of pushing it directly to PyPi.

**Comment by jkehler** [comment]
Merged and uploaded to Pypi. Thanks.

**Pull request merged**
